# Generated by Django 4.2.16 on 2024-09-16 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balancete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balanome', models.CharField(max_length=100)),
                ('baladata', models.DateField(verbose_name='Data de Publicação:')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receitanome', models.CharField(max_length=100)),
                ('receitavalor', models.IntegerField(default=0)),
                ('balancete', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.balancete')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despesanome', models.CharField(max_length=100)),
                ('despesavalor', models.IntegerField(default=0)),
                ('balancete', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.balancete')),
            ],
        ),
    ]
