# Generated by Django 4.2.16 on 2024-09-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancete',
            name='balafoto',
            field=models.ImageField(blank=True, null=True, upload_to='balancetes/'),
        ),
    ]
