# Generated by Django 4.2.16 on 2024-09-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_balanome_balancete_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancete',
            old_name='baladata',
            new_name='Data',
        ),
        migrations.RenameField(
            model_name='balancete',
            old_name='balafoto',
            new_name='Foto',
        ),
    ]
