# Generated by Django 4.2.16 on 2024-09-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_baladata_balancete_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='despesanome',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='despesa',
            old_name='despesavalor',
            new_name='Valor',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='receitanome',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='receitavalor',
            new_name='Valor',
        ),
    ]
